### recuperar movies
GET http://localhost:3000/movies

### recuperar una movie
GET http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### recuperar movies con filtro
GET http://localhost:3000/movies?year=2008

